// Class automatically generated by Dev-C++ New Class wizard

#include "app.h" // class's header file
#include <iostream>

App::App()
{
	
}

// class destructor
App::~App()
{
	// insert your code here
}

bool Sandbox::core()
{
Board* boardp;
string input;
int output;
bool quit = false;
while (quit == false)
{
    cin >> input;
    if (input == "crtBrd")
    {
        int width;
        int height;
        cin >> width;
        cin >> height;
        boardp = new Board(width, height);
    }
    else if (input == "crtBlp")
    {
        int id;
        int xloc;
        int yloc;
        cin >> id;
        cin >> xloc;
        cin >> yloc;
        boardp->create_blip(id, xloc, yloc);
    }
    else if (input == "chkLocId")
    {
        int xloc;
        int yloc;
        cin >> xloc;
        cin >> yloc;
        output = boardp->checkLocId(xloc, yloc);
    }
    else if (input == "movBlpLoc")
    {
        int curX;
        int curY;
        int newX;
        int newY;
        cin >> curX;
        cin >> curY;
        cin >> newX;
        cin >> newY;
        output = boardp->move_by_loc(curX, curY, newX, newY);
    }
    else if (input == "sftBlpLoc")
    {
        int curX;
        int curY;
        int dir;
        cin >> curX;
        cin >> curY;
        cin >> dir;
        boardp->dir_move_by_loc(curX,curY,dir);   
    }    
    else if (input == "qqq")
    {
        quit = true;
    }
        
}
}

bool Pulse :: core()
{
     cout << "Welcome to pulse";
}
