// Class automatically generated by Dev-C++ New Class wizard

#include "blip.h" // class's header file
#include "board.h"


// class constructor
Blip::Blip(Board* boardp, int type, int startx, int starty)
{
	xloc = startx;
	yloc = starty;
	id = type;
    tag = 'x';
}

// gets x position
int Blip::getX()
{
    return xloc;
}

//gets y position
int Blip::getY()
{
    return yloc;
}

// Changes internal location
void Blip::move(int newX, int newY)
{
    xloc = newX;
    yloc = newY;
}

// gets name
char Blip::getTag()
{
    return tag;
}

// sets name
int Blip::setTag(char newTag)
{
    tag = newTag;
}

// class destructor
Blip::~Blip()
{
}
