// Class automatically generated by Dev-C++ New Class wizard

#ifndef BLIP_H
#define BLIP_H

/*
 A Blip, a generic name for a unit in the game
 */
class Board;
class Blip
{
	public:
        int id;
        int xloc;
        int yloc;
		// class constructor
		Blip(Board* boardp, int id,int startx, int starty);
		// returns x location
		int getX();
		// returns y location
		int getY();
		// class destructor
		~Blip();
		// Change internal blip location
	    void move(int newX, int newY);
};

#endif // BLIP_H
