// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOARD_H
#define BOARD_H
#ifndef NULL
#define NULL 0
#endif

/*
 * No description
 */
class Blip;
class Board
{
	public:
        // creating the grid
        Blip*** grid;
        int width;
        int height;
		// class constructor
		Board(int w, int h);
		// returns width
		int getWidth();
		// returns height
		int getHeight();
		// check if given coordinates are allowed to have the given action performed on them
		int isAllowed(int xpos, int ypos);
		// check if given coordinates are within the parameters of the board
		int inBound(int xpos, int ypos);
		// create a blip
		int create_blip(int id, int xpos, int ypos);
		// check if there's a blip at some location with given id
        int checkIfBlipId(int id, int xpos, int ypos);
        // Move a Blip by its pointer id
        int move_by_id(Blip* someBlip, int newX, int newY);
        // Move a Blip by its coordinates
        int move_by_loc(int curX, int curY, int newX, int newY);
        // Directional movement of a blip by coordinates
        int dir_move_by_loc(int curX, int curY, int dir);
        // print the grid
		int dev_print_bin();
        // class destructor
		~Board();
};


#endif // BOARD_H
