// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOARD_H
#define BOARD_H
#ifndef NULL
#define NULL 0
#endif

/*
 * No description
 */
class Blip;
class Board
{
	public:
        // creating the grid
        Blip*** grid;
        int width;
        int height;
		// class constructor
		Board(int w, int h);
		// initializes the board
		int initBoard();
		// returns width
		int getWidth();
		// returns height
		int getHeight();
		// check if given coordinates are allowed to have the given action performed on them
		int isAllowed(int xpos, int ypos);
		// check if given coordinates are within the parameters of the board
		int inBound(int xpos, int ypos);
		// create a blip
		int create_blip(int id, int xpos, int ypos);
		// checks the ID of a blip at the given location. Outputs 0 if no blip
        int checkLocId(int xpos, int ypos);
        // Move a Blip by its pointer id
        int move_by_id(Blip* someBlip, int newX, int newY);
        // Move a Blip by its coordinates
        int move_by_loc(int curX, int curY, int newX, int newY);
        // Directional movement of a blip by coordinates
        int dir_move_by_loc(int curX, int curY, int dir);
        // print the grid in the binary fashon
		int dev_print_bin();
		// print the ids of each space in the grid
		int dev_print_id();
		// Prints the board much like an ordinary gameboard, with columns labeled by letters and rows denoted by numbers
		int draw_game_board();
		//checks how far the closest blip in a given direction is
		int checkClosestDir(Blip* source, int dir);
		
		
        // class destructor
		~Board();
};


#endif // BOARD_H
