// Class automatically generated by Dev-C++ New Class wizard

#ifndef LOCATION_H
#define LOCATION_H

/*
 * No description
 */
class Location
{
	public:
        int x;
        int y;
		// class constructor
		Location(int newX,int newY);
		// class destructor
		~Location();
};

#endif // LOCATION_H
