// Class automatically generated by Dev-C++ New Class wizard

#include "location.h" // class's header file

// class constructor
Location::Location(int newX,int newY)
{
    x = newX;
    y = newY;
}

// class destructor
Location::~Location()
{
	// insert your code here
}
